"""add user weight

Revision ID: 84401b14fd0a
Revises: dfddd1819a95
Create Date: 2024-08-24 21:23:06.531681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84401b14fd0a'
down_revision = 'dfddd1819a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
