"""add current

Revision ID: c90e178637e0
Revises: f52d5077dd17
Create Date: 2024-08-25 22:58:38.112059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90e178637e0'
down_revision = 'f52d5077dd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_protein_cal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_carb_cal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_fat_cal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('current_fat_cal')
        batch_op.drop_column('current_carb_cal')
        batch_op.drop_column('current_protein_cal')

    # ### end Alembic commands ###
